#!/usr/bin/env Rscript

# Main Discriminant Analysis Script
# Comprehensive testing of all discriminants in discriminants.csv
# 
# This script performs extensive statistical testing on random numbers generated
# using each discriminant configuration from the discriminants.csv file.
# 
# Usage:
#   Rscript run_discriminant_analysis.R [sample_size] [max_discriminants]
#
# Arguments:
#   sample_size: Number of random samples to generate per discriminant (default: 1000000)
#   max_discriminants: Maximum number of discriminants to test (default: 750)

# Load required libraries and source files
suppressPackageStartupMessages({
  library(qiprng)
  library(moments)
  library(nortest)
  library(ggplot2)
  library(gridExtra)
})

# Source our testing modules from the project root
source("R/discriminant_tests.R")
source("R/discriminant_reports.R")
source("R/excellent_discriminants.R")

# Parse command line arguments
args <- commandArgs(trailingOnly = TRUE)
if (length(args) >= 1) {
  sample_size <- as.numeric(args[1])
} else {
  sample_size <- 1000000
}
if (length(args) >= 2) {
  if (args[2] == "NULL" || args[2] == "null" || args[2] == "all") {
    max_discriminants <- NULL
  } else {
    max_discriminants <- as.numeric(args[2])
  }
} else {
  max_discriminants <- NULL
}
if (length(args) >= 3) {
  n_cores <- as.numeric(args[3])
} else {
  n_cores <- NULL
}

# Configuration
cat("=== QIPRNG Discriminant Analysis ===\n")
cat("Sample size per discriminant:", sample_size, "\n")
cat("Max discriminants to test:", ifelse(is.null(max_discriminants), "All", max_discriminants), "\n")
cat("Output directory: discriminant_analysis_results/\n\n")

# Verify discriminants file exists
discriminants_path <- "analysis/data/discriminants.csv"
if (!file.exists(discriminants_path)) {
  stop("Error: discriminants.csv not found at ", discriminants_path)
}

# Quick preview of discriminants
cat("Preview of discriminants.csv:\n")
preview <- read.csv(discriminants_path, nrows = 5)
print(preview)
cat("...\n")
total_discriminants <- nrow(read.csv(discriminants_path))
cat("Total discriminants available:", total_discriminants, "\n\n")

# Run the comprehensive analysis
cat("Starting comprehensive discriminant analysis...\n")
cat("This will test statistical properties of random numbers generated by each discriminant.\n")
cat("Tests include: Uniformity, Independence, Autocorrelation, Periodicity, and Moment Analysis.\n\n")

start_time <- Sys.time()

# Execute the main analysis
results <- run_discriminant_analysis(
  discriminants_file = discriminants_path,
  sample_size = sample_size,
  max_discriminants = max_discriminants,
  n_cores = n_cores
)

end_time <- Sys.time()
analysis_duration <- difftime(end_time, start_time, units = "mins")

cat("\nAnalysis completed in", round(as.numeric(analysis_duration), 2), "minutes\n\n")

# Generate and save comprehensive reports
cat("Generating reports and visualizations...\n")
analysis_output <- save_analysis_results(results, "analysis/results/discriminant_analysis_results")

# Print summary to console
summary_data <- analysis_output$summary_data

cat("\n=== ANALYSIS SUMMARY ===\n")
cat("Total discriminants tested:", nrow(summary_data), "\n")
cat("Successful tests:", sum(summary_data$quality_rating != "Error"), "\n")
cat("Failed/Error tests:", sum(summary_data$quality_rating == "Error"), "\n\n")

# Quality distribution
quality_counts <- table(summary_data$quality_rating)
cat("Quality Distribution:\n")
for (rating in names(quality_counts)) {
  percentage <- round(100 * quality_counts[rating] / nrow(summary_data), 1)
  cat(sprintf("  %s: %d (%s%%)\n", rating, quality_counts[rating], percentage))
}

# Test pass rates
cat("\nTest Pass Rates:\n")
cat(sprintf("  Uniformity: %.1f%%\n", 100 * mean(summary_data$uniformity_passed, na.rm = TRUE)))
cat(sprintf("  Independence: %.1f%%\n", 100 * mean(summary_data$independence_passed, na.rm = TRUE)))
cat(sprintf("  Autocorrelation: %.1f%%\n", 100 * mean(summary_data$autocorrelation_passed, na.rm = TRUE)))
cat(sprintf("  Periodicity: %.1f%%\n", 100 * mean(summary_data$periodicity_passed, na.rm = TRUE)))

# Top performers
cat("\nTop 5 Performing Discriminants:\n")
top_indices <- order(summary_data$overall_score, decreasing = TRUE)[1:5]
for (i in 1:5) {
  if (i <= length(top_indices)) {
    row <- summary_data[top_indices[i], ]
    cat(sprintf("  #%d: a=%d, b=%d, c=%d, Δ=%d (Score: %.3f)\n", 
                row$index, row$a, row$b, row$c, row$discriminant, row$overall_score))
  }
}

# Statistical insights
cat("\nStatistical Insights:\n")
cat(sprintf("  Mean overall score: %.3f\n", mean(summary_data$overall_score, na.rm = TRUE)))
cat(sprintf("  Median overall score: %.3f\n", median(summary_data$overall_score, na.rm = TRUE)))
cat(sprintf("  Standard deviation: %.3f\n", sd(summary_data$overall_score, na.rm = TRUE)))

# Correlation analysis
valid_data <- summary_data[!is.na(summary_data$overall_score) & summary_data$overall_score > 0, ]
if (nrow(valid_data) > 10) {
  discriminant_cor <- cor(valid_data$discriminant, valid_data$overall_score)
  a_cor <- cor(valid_data$a, valid_data$overall_score)
  abs_c_cor <- cor(abs(valid_data$c), valid_data$overall_score)
  
  cat("\nParameter Correlations with Quality Score:\n")
  cat(sprintf("  Discriminant value: %.3f\n", discriminant_cor))
  cat(sprintf("  Parameter a: %.3f\n", a_cor))
  cat(sprintf("  |Parameter c|: %.3f\n", abs_c_cor))
}

cat("\n=== OUTPUTS GENERATED ===\n")
cat("All results saved to: ../results/discriminant_analysis_results/\n")
cat("Key files:\n")
cat("  - summary_statistics.csv: Tabular results for all discriminants\n")
cat("  - detailed_report.md: Comprehensive analysis report\n")
cat("  - combined_analysis.png: Overview visualization\n")
cat("  - Individual test visualizations (PNG files)\n")
cat("  - raw_results.rds: Complete R data for further analysis\n\n")

# Recommendations
cat("=== RECOMMENDATIONS ===\n")
excellent_count <- sum(summary_data$quality_rating == "Excellent", na.rm = TRUE)
good_count <- sum(summary_data$quality_rating == "Good", na.rm = TRUE)

if (excellent_count > 0) {
  cat("✓ Found", excellent_count, "excellent discriminants - these are recommended for production use\n")
}
if (good_count > 0) {
  cat("✓ Found", good_count, "good discriminants - suitable for most applications\n")
}

poor_count <- sum(summary_data$quality_rating %in% c("Poor", "Fair"), na.rm = TRUE)
if (poor_count > 0) {
  cat("⚠ Found", poor_count, "poor/fair discriminants - consider avoiding these\n")
}

error_count <- sum(summary_data$quality_rating == "Error", na.rm = TRUE)
if (error_count > 0) {
  cat("✗ Found", error_count, "discriminants that caused errors - investigate these\n")
}

cat("For detailed analysis, see: ./results/discriminant_analysis_results/detailed_report.md\n")
cat("For visualizations, see PNG files in: ./results/discriminant_analysis_results/\n")

cat("\n=== ANALYSIS COMPLETE ===\n")

# Load and display excellent discriminants summary
cat("\n", paste(rep("=", 50), collapse=""), "\n")
cat("EXCELLENT DISCRIMINANTS ANALYSIS\n")
cat(paste(rep("=", 50), collapse=""), "\n")

tryCatch({
  print_excellent_summary("analysis/results/discriminant_analysis_results/raw_results.rds")
  
  cat("\n=== PRODUCTION RECOMMENDATIONS ===\n")
  cat("The analysis identified excellent discriminants suitable for production use.\n")
  cat("These discriminants have passed rigorous statistical testing and show superior randomness quality.\n\n")
  
  cat("To use excellent discriminants in your code:\n")
  cat("\n# Load the excellent discriminants module\n")
  cat("source('R/excellent_discriminants.R')\n\n")
  
  cat("# Get top 10 recommended discriminants\n")
  cat("recommended <- get_recommended_discriminants(n=10, criteria='balanced')\n\n")
  
  cat("# Generate random numbers using the best discriminant\n")
  cat("samples <- generate_excellent_random(n=50000, discriminant_index=1)\n\n")
  
  cat("# Create PRNG config for production use\n")
  cat("excellent <- load_excellent_discriminants()\n")
  cat("config <- create_excellent_prng_config(excellent[1,], precision=256)\n")
  cat("createPRNG(config=config)\n")
  cat("random_numbers <- generatePRNG(10000)\n\n")
  
}, error = function(e) {
  cat("Note: Excellent discriminants analysis requires completed results.\n")
  cat("Run the full analysis first to access the 227 excellent discriminants.\n")
})

cat("\n=== QUARTO REPORT GENERATION ===\n")
cat("To generate the comprehensive Quarto report:\n")
cat("\n# In R or RStudio:\n")
cat("quarto::quarto_render('discriminant_analysis_report.qmd')\n\n")
cat("# Or from command line:\n")
cat("quarto render analysis/reports/discriminant_analysis_report.qmd\n\n")
cat("This will create an interactive HTML report with detailed analysis and visualizations.\n")

cat("\n=== ANALYSIS COMPLETE ===\n")
