# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.createPRNG_ <- function(cfg) {
    invisible(.Call(`_qiprng_createPRNG_`, cfg))
}

.updatePRNG_ <- function(cfg) {
    invisible(.Call(`_qiprng_updatePRNG_`, cfg))
}

.generatePRNG_ <- function(n) {
    .Call(`_qiprng_generatePRNG_`, n)
}

.reseedPRNG_ <- function() {
    invisible(.Call(`_qiprng_reseedPRNG_`))
}

.cleanup_prng_ <- function() {
    invisible(.Call(`_qiprng_cleanup_prng_`))
}

