# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.initialize_libsodium_ <- function() {
    invisible(.Call(`_qiprng_initialize_libsodium_`))
}

.createPRNG_ <- function(rcfg) {
    invisible(.Call(`_qiprng_createPRNG_`, rcfg))
}

.updatePRNG_ <- function(rcfg) {
    invisible(.Call(`_qiprng_updatePRNG_`, rcfg))
}

.getPRNGConfig_ <- function() {
    .Call(`_qiprng_getPRNGConfig_`)
}

.dumpPRNGConfig_ <- function() {
    invisible(.Call(`_qiprng_dumpPRNGConfig_`))
}

.generatePRNG_ <- function(n) {
    .Call(`_qiprng_generatePRNG_`, n)
}

.reseedPRNG_ <- function() {
    invisible(.Call(`_qiprng_reseedPRNG_`))
}

.cleanup_prng_ <- function() {
    invisible(.Call(`_qiprng_cleanup_prng_`))
}

.skipPRNG_ <- function(n) {
    invisible(.Call(`_qiprng_skipPRNG_`, n))
}

.jumpAheadPRNG_ <- function(n) {
    invisible(.Call(`_qiprng_jumpAheadPRNG_`, n))
}

.suppress_mpfr_warnings_ <- function() {
    .Call(`_qiprng_suppress_mpfr_warnings_`)
}

.set_mpfr_warnings_ <- function(show_warnings) {
    invisible(.Call(`_qiprng_set_mpfr_warnings_`, show_warnings))
}

.cleanupPRNG_ThreadSafe_ <- function() {
    .Call(`_qiprng_cleanupPRNG_ThreadSafe_`)
}

.cleanupPRNG_Final_ <- function() {
    .Call(`_qiprng_cleanupPRNG_Final_`)
}

test_choose_discriminant <- function(thread_count = 4L, iterations = 10L) {
    .Call(`_qiprng_test_choose_discriminant`, thread_count, iterations)
}

check_discriminants_unique <- function(discriminant_lists) {
    .Call(`_qiprng_check_discriminants_unique`, discriminant_lists)
}

